name: slang_flutter
description: Flutter support for slang. This library provides helpful Flutter API.
version: 4.4.0
repository: https://github.com/slang-i18n/slang

environment:
  flutter: '>=3.19.0'
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Use a tight version to ensure that all features are available
  slang: '>=4.4.0 <4.5.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
